---
# NOTE: To install dependencies use command:
# ansible-galaxy install -r requirements.yaml

collections:
  - name: community.general
  - name: community.crypto
  - name: community.postgresql
  - name: community.mysql
  - name: community.network
