all:
  vars:
    sf_version: master
    zuul:
      branch: master
      projects:
        opendev.org/opendev/elastic-recheck:
          src_dir: "~{{ ansible_user }}/elastic-recheck"
        opendev.org/openstack/ci-log-processing:
          src_dir: "~{{ ansible_user }}/ci-log-processing"
        softwarefactory-project.io/software-factory/ansible-role-elastic-recheck:
          src_dir: "~{{ ansible_user }}/ansible/role-elastic-recheck"
        softwarefactory-project.io/software-factory/sf-ci:
          name: software-factory/sf-ci
          src_dir: "~{{ ansible_user }}/sf-ci"
        softwarefactory-project.io/software-factory/sf-config:
          name: software-factory/sf-config
          src_dir: "~{{ ansible_user }}/sf-config"
        softwarefactory-project.io/software-factory/sfinfo:
          name: software-factory/sfinfo
          src_dir: "~{{ ansible_user }}/sfinfo"
        softwarefactory-project.io/software-factory/sf-infra:
          name: software-factory/sf-infra
          src_dir: "{{ ansible_user }}/sf-infra"
        # edpm
        github.com/openstack-k8s-operators/install_yamls:
          name: openstack-k8s-operators/install_yamls
          src_dir: "~{{ ansible_user }}/src/github.com/openstack-k8s-operators/install_yamls"
        github.com/openstack-k8s-operators/edpm-ansible:
          name: openstack-k8s-operators/edpm-ansible
          src_dir: "~{{ ansible_user }}/src/github.com/openstack-k8s-operators/edpm-ansible"
        github.com/openstack-k8s-operators/openstack-ansibleee-operator:
          name: openstack-k8s-operators/openstack-ansibleee-operator
          src_dir: "~{{ ansible_user }}/src/github.com/openstack-k8s-operators/openstack-ansibleee-operator"
        github.com/openstack-k8s-operators/openstack-operator:
          name: openstack-k8s-operators/openstack-operator
          src_dir: "~{{ ansible_user }}/src/github.com/openstack-k8s-operators/openstack-operator"
  hosts:
    microshift.dev:
      ansible_port: 22
      ansible_host: 192.168.122.202
      ansible_user: centos
