all:
  vars:
    sf_version: master
    zuul:
      branch: master
      projects:
        opendev.org/opendev/elastic-recheck:
          src_dir: /home/centos/elastic-recheck
        opendev.org/openstack/ci-log-processing:
          src_dir: /home/centos/ci-log-processing
        softwarefactory-project.io/software-factory/ansible-role-elastic-recheck:
          src_dir: /home/centos/ansible/role-elastic-recheck
        softwarefactory-project.io/software-factory/sf-ci:
          name: software-factory/sf-ci
          short_name: sf-ci
          src_dir: /home/centos/sf-ci
        softwarefactory-project.io/software-factory/sf-config:
          name: software-factory/sf-config
          short_name: sf-config
          src_dir: /home/centos/sf-config
        softwarefactory-project.io/software-factory/sfinfo:
          name: software-factory/sfinfo
          short_name: sfinfo
          src_dir: /home/centos/sfinfo
        softwarefactory-project.io/software-factory/sf-infra:
          name: software-factory/sf-infra
          short_name: sf-infra
          src_dir: /home/centos/sf-infra
  hosts:
    microshift.dev:
      ansible_port: 22
      ansible_host: 192.168.122.202
      ansible_user: centos
