all:
  children:
    peers:
      hosts:
        elk: null
    switch:
      hosts:
        master: null
  vars:
    sf_version: master
    zuul:
      projects:
        opendev.org/opendev/elastic-recheck:
          src_dir: /home/centos/elastic-recheck
        opendev.org/openstack/ci-log-processing:
          src_dir: /home/centos/ci-log-processing
  hosts:
    elk:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: centos
    master:
      ansible_host: localhost
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python2
      ansible_user: centos
      show_hidden_logs: true
    quay.dev:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: centos
    opensearch.dev:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: centos
