all:
  children:
    peers:
      hosts:
        elk: null
    switch:
      hosts:
        master: null
  vars:
    sf_version: master
    zuul:
      branch: master
      projects:
        opendev.org/opendev/elastic-recheck:
          src_dir: "/home/centos/elastic-recheck"
        opendev.org/openstack/ci-log-processing:
          src_dir: "/home/centos/ci-log-processing"
        softwarefactory-project.io/software-factory/ansible-role-elastic-recheck:
          src_dir: "/home/centos/ansible-role-elastic-recheck"
        softwarefactory-project.io/software-factory/sf-ci:
          name: software-factory/sf-ci
          short_name: sf-ci
          src_dir: /home/centos/sf-ci
        softwarefactory-project.io/software-factory/sf-config:
          name: software-factory/sf-config
          short_name: sf-config
          src_dir: /home/centos/sf-config
        softwarefactory-project.io/software-factory/sfinfo:
          name: software-factory/sfinfo
          short_name: sfinfo
          src_dir: /home/centos/sfinfo
  hosts:
    elk:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: centos
    master:
      ansible_host: localhost
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python2
      ansible_user: centos
      show_hidden_logs: true
    zs:
      ansible_host: localhost
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python2
      ansible_user: centos
      show_hidden_logs: true
    ze:
      ansible_host: localhost
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python2
      ansible_user: centos
      show_hidden_logs: true
    install-server:
      ansible_host: localhost
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python2
      ansible_user: centos
      show_hidden_logs: true
    quay.dev:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: centos
    opensearch.dev:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: centos
    kind.dev:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: centos
