---
- name: Install Ansible, Make, Tar
  become: true
  ansible.builtin.package:
    name:
      - ansible-core
      - make
      - tar
      - vim
    state: latest

- name: Install devsetup dependencies
  community.general.make:
    chdir: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}/devsetup"
    target: download_tools

#- name: Deploy Openstack Operators
#  community.general.make:
#    chdir: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}"
#    target: openstack
#    params:
#      OUT: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}/out"
#      MICROSHIFT: 1

- name: Deploy Openstack Operators
  ansible.builtin.shell: |
    make openstack
  args:
    chdir: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}"
  environment:
    MICROSHIFT: 1
#    OUT: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}/out"


- name: Wait for operator to get deployed
  ansible.builtin.shell: |
    oc get csv --no-headers=true | grep -i "succeeded"
  register: operator_status
  until: operator_status.rc == 0
  retries: 20
  delay: 5

- name: Print Operator Status
  ansible.builtin.shell: |
    oc get csv;
    oc get pods;

#- name: Deploy OpenStack Services
#  community.general.make:
#    chdir: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}"
#    target: openstack_deploy
#    params:
#      OUT: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}/out"
#      MICROSHIFT: 1
#      OPENSTACK_REPO: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/openstack-operator"

- name: Deploy OpenStack Services
  ansible.builtin.shell: |
    make openstack_deploy
  args:
    chdir: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}"
  environment:
    MICROSHIFT: 1
#    OUT: "{{ zuul.projects['github.com/openstack-k8s-operators/install_yamls'].src_dir }}/out"
#    OPENSTACK_REPO: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/openstack-operator"

- name: Wait for OpenStack Services to deployed
  ansible.builtin.shell: |
    # Cinder is disabled due to missing ceph support
    oc get OpenStackControlPlane openstack -o json | jq -r '.status.conditions[].type';
    oc get OpenStackControlPlane openstack -o json | \
    jq -r '.status.conditions[] | select(.type | test("^OpenStackControlPlane(?!Cinder)")).type' | \
    timeout 240 xargs -d '\n' -I {} sh -c 'echo testing condition={}; \
    oc wait openstackcontrolplane.core.openstack.org/openstack --for=condition={} --timeout=-1s'
  ignore_errors: true

- name: Print Pod Status
  ansible.builtin.shell: |
    oc get pods;
