---
- hosts: quay.dev
  vars:
    hide_sensitive_logs: false
    enable_clair: false
    enable_mirror: false
    fqdn: quay.dev
    self_signed_certs: true
    initial_config: true
    quay_validate_cert: false
    # user spaces
    quay_users:
      admin:
        email: admin@quay.dev
        password: password
        token: ""
      someuser:
        email: someuser@someemail.com
        token: ""
    # user ogranization + robot tokens
    quay_organizations:
      someuser:
        - name: myorganization1
          token: ""
        - name: myorganization2
          token: ""
    database_secret_key: 58995dde-5a37-53a1-ab79-835dfa2bc701
    secret_key: 171e632d-c0a6-56ac-be90-5ee27d283d5d
    postgresql_additional_parameters: "-c shared_buffers=256MB -c max_connections=2000"
    container_images:
      quay: quay.io/projectquay/quay:v3.7.10
      postgresql: quay.io/software-factory/postgres:13.5-alpine3.14
      clair: quay.io/projectquay/clair:4.3.5
      redis: quay.io/software-factory/redis:6.2.4
    quay_enable_prune: true
    quay_api_url: https://quay.dev/api/v1
    quay_insecure: true
  pre_tasks:
    - name: Disable ipv6
      become: true
      shell: |
        sysctl -w net.ipv6.conf.all.disable_ipv6=1 ; sysctl -w net.ipv6.conf.default.disable_ipv6=1

    - include_role:
        name: service/hostname

    - name: Install epel-release
      become: true
      package:
        name: epel-release
        state: present
      ignore_errors: true

    - name: Install python3-bcrypt
      become: true
      package:
        name:
          - python3
          - python3-bcrypt
          - python3-cryptography
        state: present

    - name: remove epel-release
      become: true
      package:
        name: epel-release
        state: absent
  tasks:
    - name: Setup quay
      include_role:
        name: rdo/quay
        tasks_from: main.yml

    - name: Create organizations
      include_role:
        name: rdo/quay-project-creation
        tasks_from: main.yml
