---
# WARNING: Bootstrap Quay by using playbook: https://github.com/danpawlik/my-playbooks/blob/master/playbooks/sf/quay.yml
# After setup, create project as `sf` user (password is in /var/data/quay/config/sf_token):
#  * config_sf
# Then inside the `config_sf` create application:
#  * admin_token
# with privileges:
#  * "Administer Organization",
#  * "Administer Repositories",
#  * "Create Repositories",
#  * "View all visible repositories",
#  * "Read/Write to any accessible repositories",
#  * "Administer User" permissions.
#
#  NOTE: if you have problems in your dev deployment on getting the
#  token because of the HSTS, change the hostname address (from quay.dev) to ip address.
#
# Same steps for tripleo user (password is in: /var/data/quay/config/tripleo_token).
# After getting a token, add value into the "quay_users" ansible var below and re-run playbook https://github.com/danpawlik/my-playbooks/blob/master/playbooks/sf/quay.yml
# (because you need to create admin_token and provide it in playbook).
- hosts: quay.dev
  vars:
    enable_clair: true
    enable_mirror: true
    fqdn: quay.dev
    self_signed_certs: true
    initial_config: false
    quay_validate_cert: false
    # will be removed soon
    quay_admin_password: password
    quay_users:
      admin:
        email: admin@quay.dev
        password: password
      # Provide token after bootstrap via creating "new application" with proper privileges.
      # More info: https://www.softwarefactory-project.io/deploying-the-quay-container-registry.html
      sf:
        email: sf@quay.dev
        password: password
        # token: ''
        token: 'ddDQiIlVaeV9ZLOXpgPHgVBQgOjHb4ljakV7jrht'
      tripleo:
        email: tripleo@quay.dev
        password: password
        #token: ''
        token: WfoXbwAS0izIdgaeW6VwHKUJE2UPXePtrE4m8bdB
    database_secret_key: 12995dde-5a37-53a1-ab79-123dfa2bc701
    secret_key: 123632d-c0a6-56ac-be90-12347d283d12
    postgresql_additional_parameters: "-c shared_buffers=256MB -c max_connections=2000"
    container_images:
      postgresql: quay.io/software-factory/postgres:13.12-alpine3.18
      redis: quay.io/software-factory/redis:7.2.0-alpine3.18
      quay: quay.io/projectquay/quay:v3.10.0
      clair: quay.io/projectquay/clair:4.7.2
    quay_enable_prune: true
    quay_api_url: https://quay.dev/api/v1
    quay_insecure: true
    quay_organizations:
      # pruner
      tripleo:
        - name: tripleomastercentos9
          token: ""
          prune_days: 7
        - name: tripleotraincentos8
          token: ""
          prune_days: 7
        - name: tripleotraincentos7
          token: ""
          prune_days: 7
        - name: tripleowallabycentos9
          token: ""
          prune_days: 7
        - name: tripleowallabycentos8
          token: ""
          prune_days: 7
  pre_tasks:
    - name: Disable ipv6
      become: true
      shell: |
        sysctl -w net.ipv6.conf.all.disable_ipv6=1 ; sysctl -w net.ipv6.conf.default.disable_ipv6=1

    - include_role:
        name: service/hostname

    - name: Install epel-release
      become: true
      package:
        name: epel-release
        state: present
      ignore_errors: true

    - name: Install python3-bcrypt
      become: true
      package:
        name:
          - python3
          - python3-bcrypt
          - python3-cryptography
        state: present

    - name: remove epel-release
      become: true
      package:
        name: epel-release
        state: absent
  tasks:
    - name: Setup quay
      include_role:
        name: rdo/quay
        tasks_from: main.yml
    - name: Create organizations
      include_role:
        name: rdo/quay-project-creation
        tasks_from: main.yml
