---
- name: Run sf-operator
  hosts: microshift.dev,kubernetes.dev,crc.dev
  vars:
    operator_dir: ~/sf-operator
    git_command: ""
    namespace: default
    storageclass: standard
  tasks:
    - name: Clone dir
      git:
        repo: https://softwarefactory-project.io/r/software-factory/sf-operator
        dest: "{{ operator_dir }}"
      ignore_errors: true

    - name: Checkout on patch or cherry-pick etc
      shell: |
        {{ git_command }}
      args:
        chdir: "{{ operator_dir }}"
      when: git_command != ''

    - name: Install requires go packages
      shell: |
        make install
      args:
        chdir: "{{ operator_dir }}"

    - name: Install cert manager
      shell: |
        make install-cert-manager
      args:
        chdir: "{{ operator_dir }}"

    - name: Get namespace
      shell: |
        NS=$(/usr/local/bin/kubectl config view -o jsonpath='{.contexts[].context.namespace}')
        if [ -z "${NS}" ]; then
            NS="default"
        fi
        echo "${NS}"
      register: _ns
      when: namespace is not defined and namespace == ''

    - name: Set namespace var
      set_fact:
        namespace: "{{ _ns.stdout }}"
      when: namespace is not defined and namespace == ''

    - name: Change namespace
      shell: |
        cp config/samples/sf_v1_softwarefactory.yaml my-sf.yaml
        sed -i "s/fqdn: \"sftests.com\"/fqdn: \"{{ namespace }}\"/g" my-sf.yaml
      args:
        chdir: "{{ operator_dir }}"

    - name: Enable all services
      shell: |
        sed -i 's/false/true/g' my-sf.yaml
      args:
        chdir: "{{ operator_dir }}"

    - name: Change storageclass
      shell: |
        find {{ operator_dir }} -type f -exec sed -i "s/standard/{{ storageclass }}/g" {} \;
      when: storageclass != 'standard'

    - name: Run operator deployment
      shell: |
        go run ./main.go --namespace {{ namespace }} --cr ./my-sf.yaml
      args:
        chdir: "{{ operator_dir }}"
