---
- hosts: opensearch.dev
  become: true
  vars:
    # logscraper
    tenant_builds:
      - tenant: openstack
        zuul_api_url: https://zuul.opendev.org/api/tenant/openstack
        zuul_api_urls:
          - https://zuul.opendev.org/api/tenant/openstack
        insecure: false
        job_names: []
        download: true
        download_dir: /mnt/logscraper/openstack
        es_username: admin
        es_password: admin
        es_host: localhost
        es_port: 9200
        es_insecure: true
        es_index: logstash-logscraper
        logscraper_dir: /etc/logscraper
    zuul:
      projects:
        opendev.org/openstack/ci-log-processing:
          src_dir: /home/centos/ci-log-processing
  pre_tasks:
    - name: Update all packages
      become: true
      package:
        name: "*"
        state: latest
  tasks:
    - name: Run check services
      include_role:
        name: check-services
        tasks_from: download.yml
