---
- hosts: opensearch.dev
  become: true
  pre_tasks:
    - name: Update all packages
      become: true
      package:
        name: "*"
        state: latest

    - name: Install rsync package
      become: true
      package:
        name:
          - rsync
          - git
        state: present

    - name: Clone required projects
      git:
        repo: https://opendev.org/openstack/ci-log-processing
        dest: /home/centos/ci-log-processing
        clone: true
        update: false

    - name: Clone required projects
      git:
        repo: https://opendev.org/opendev/elastic-recheck
        dest: /home/centos/elastic-recheck
        version: rdo
        clone: true
        update: false

    - name: Synchronize required projects
      synchronize:
        src: "{{ playbook_dir }}/../../external_projects/ci-log-processing/"
        dest: "/home/centos/ci-log-processing/"
        recursive: true
        archive: true
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git"

- name: Run check services
  import_playbook: ../../external_projects/ci-log-processing/ansible/playbooks/check-services-elasticrecheck.yml
