---
- hosts: quay.dev
  vars:
    container_registry_logins:
      quay.dev:
        test: "test"
    tripleo_container_registry_logins: '{{ container_registry_logins }}'
    tripleo_podman_tls_verify: false
  tasks:
    - name: Perform container registry login(s) with podman
      become: true
      shell: |-
        podman login --username=$REGISTRY_USERNAME \
                     --password=$REGISTRY_PASSWORD \
                     --tls-verify={{ tripleo_podman_tls_verify }} \
                     $REGISTRY | tee /tmp/dump-login
      environment:
        REGISTRY_USERNAME: "{{ lookup('dict', item.value).key }}"
        REGISTRY_PASSWORD: "{{ lookup('dict', item.value).value }}"
        REGISTRY: "{{ item.key }}"
      no_log: false
      loop: "{{ query('dict', tripleo_container_registry_logins) }}"
