---
- name: check registry login
  hosts: quay.dev
  become: true
  vars:
    tripleo_podman_tls_verify: false
    container_registry_logins:
      quay.rdoproject.org:
        tripleomastercentos9+tripleomastercentos9: "test"
    tripleo_container_registry_logins: '{{ container_registry_logins }}'

  tasks:
    - name: Install podman
      package:
        name: podman
        state: present

    - name: test
      copy:
        content: |
          podman login --username={{ lookup('dict', item.value).key }} \
            --password={{ lookup('dict', item.value).value }} \
            --tls-verify={{ tripleo_podman_tls_verify }} \
            {{ item.key }}
        dest: /tmp/quay
      loop: "{{ query('dict', tripleo_container_registry_logins) }}"

    - name: Perform container registry login(s) with podman
      shell: |-
        podman login --username=$REGISTRY_USERNAME \
                     --password=$REGISTRY_PASSWORD \
                     --tls-verify={{ tripleo_podman_tls_verify }} \
                     $REGISTRY
      environment:
        REGISTRY_USERNAME: "{{ lookup('dict', item.value).key }}"
        REGISTRY_PASSWORD: "{{ lookup('dict', item.value).value }}"
        REGISTRY: "{{ item.key }}"
      loop: "{{ query('dict', tripleo_container_registry_logins) }}"
      register: registry_login_podman
