---
- name: Disable ipv6
  become: true
  shell: |
    sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sysctl -w net.ipv6.conf.default.disable_ipv6=1

- name: Change DNS servers
  become: true
  copy:
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8
    dest: /etc/resolv.conf

- name: Gather package facts
  package_facts:
    manager: auto

- name: Setup fastes mirror when available
  become: true
  copy:
    content: |
      [main]
      socket_timeout = 3
      enabled = 1
      hostfilepath = /var/cache/yum/timedhosts.txt
      maxhostfileage = 1
      always_print_best_host = true
      maxhostfileage=10
      maxthreads=16
      minrate=5M
      exclude=.wcss.pl,.wielun.net
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
  when: "'yum-plugin-fastestmirror' in ansible_facts.packages"

- name: Do Centos repository workaround
  become: true
  shell: |
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/Cent*.repo
    #sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/Cent*.repo
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://mirror.regionone.vexxhost.rdoproject.org|g' /etc/yum.repos.d/Cent*.repo
  when: "'yum-plugin-fastestmirror' not in ansible_facts.packages"

- name: Cleanup cache
  become: true
  shell: |
    yum clean all

- name: Update all packages
  become: true
  yum:
    name: '*'
    state: latest
  when: update_packages | default(true)

- name: Install base packages
  become: true
  yum:
    name:
      - git
      - rsync
    state: present

- name: Include all vars
  include_vars: group_vars/all

- name: Configure SF
  block:
    - name: Fail when buildset_artifacts_url not set
      fail:
        msg: "Please set buildset_artifacts_url"
      when: buildset_artifacts_url == ""

    - name: Configure repository
      become: true
      copy:
        content: |
          [sfmaster]
          name=sfmaster
          baseurl=http://38.102.83.102/kojifiles/repos/sf-master-el7-build/latest/x86_64/
          gpgkey=
          gpgcheck=0
          priority=110
          exclude=sf-release

          [sftesting]
          name=sftesting
          baseurl={{ buildset_artifacts_url }}
          gpgkey=
          gpgcheck=0
          priority=2
          exclude=sf-release
        dest: /etc/yum.repos.d/sf-config.repo

    - name: Setup /etc/sf-release file
      become: true
      copy:
        content: "master"
        dest: /etc/sf-release
  when: sf_install | default(true)

- name: Clone required projects
  git:
    repo: https://softwarefactory-project.io/r/software-factory/sf-ci
    dest: /home/centos/sf-ci
    clone: true
    update: false

- name: Clone required projects
  git:
    repo: https://softwarefactory-project.io/r/software-factory/ansible-role-elastic-recheck
    dest: /home/centos/ansible-role-elastic-recheck
    clone: true
    update: false

- name: Synchronize required projects
  synchronize:
    src: "{{ playbook_dir }}/../../external_projects/ansible-role-elastic-recheck/"
    dest: "/home/centos/ansible-role-elastic-recheck/"
    recursive: true
    archive: true
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"

- name: Synchronize required projects
  synchronize:
    src: "{{ playbook_dir }}/../../external_projects/sf-ci/"
    dest: "/home/centos/sf-ci/"
    recursive: true
    archive: true
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
