---
- name: Generate ssh key when not available
  block:
    - name: Generate SSH key
      openssh_keypair:
        path: /home/centos/.ssh/id_ed25519
        type: ed25519

    - name: Change permission to centos
      file:
        path: /home/centos/.ssh
        owner: centos
        group: centos
        recurse: true

    - name: Copy generated key to the root ssh
      copy:
        remote_src: true
        src: "/home/centos/.ssh/{{ item.name }}"
        dest: "/root/.ssh/{{ item.name }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - name: id_ed25519
          mode: 0600
        - name: id_ed25519.pub
          mode: 0644
