---
- hosts: install-server
  vars:
    add_k1s_hypervisor: true
    # from <CI LOG>/zuul-info/inventory.yaml
    buildset_artifacts_url: ""
    logclassify_debug: true
    logclassify_logserver_dir: logs/
    logclassify_report: true
    sf_version: master
    sf_arch: minimal
    show_hidden_logs: true
    zuul_use_fetch_output: true
    # keycloak
    show_hidden_logs: true
    add_component:
      - component: firehose
        insertafter: gateway
      - component: keycloak
        insertafter: gateway
    unsupported_components:
      - cauth
  tasks:
    # disable ipv6 and others
    - include: common.yaml

    - name: Prepare instance
      include_role:
        name: '{{ item }}'
      loop:
        - prepare-test-env
          # - install-ci-repository
        - install-sfconfig
        - configure-sfconfig

    - name: Configure hostname and fqdn
      include_role:
        name: configure-fqdn
      vars:
        domain: sfdomain.com

    - name: Run sfconfig
      include_role:
        name: run-sfconfig

    - name: Update hostname and fqdn to sftests.com
      include_role:
        name: configure-fqdn
      vars:
        domain: sftests.com

    - name: Run sfconfig to update the deployment fqdn
      include_role:
        name: run-sfconfig
      vars:
        sfconfig_args: --skip-install --provision-demo

    - name: Ensure test tools are installed
      become: true
      yum:
        name:
          - python3-nose
          - python3-nose-timer
          - python3-nose-htmloutput

    - name: Run functional tests and health-check
      include_role:
        name: '{{ item }}'
      loop:
        # - setup-test-env
        - run-provisioner
        - run-backup-create
        - run-health-check
        - run-firehose-listener
        - run-functional-tests
        - check-firehose-events

    - name: Erase the system
      include_role:
        name: run-erase

    - name: Install sfconfig package
      include_role:
        name: install-sfconfig

    - name: Restore the backup
      include_role:
        name: run-sfconfig
      vars:
        sfconfig_args: --recover

#    - name: Validate backup recovery
#      include_role:
#        name: run-checker
