---
- hosts: elk
  become: true
  vars:
    # NOTE: the hide_sensitive_logs is set to false in Zuul CI jobs.
    hide_sensitive_logs: false
    fqdn: opensearch.sftests.com
    tenant_configuration:
      sftests.com:
        kibana_autologin: "basic"
    internal_users:
      - user: "admin"
        role: "admin"
        password: "admin"
      - user: "kibanaserver"
        role: "kibanauser"
        password: "kibanaserver"
    users:
      - user: "admin"
        role: "admin"
        password: "admin"
        tenant: "sftests.com"
      - user: "logstash"
        role: "logstash"
        password: "logstash"
        tenant: "sftests.com"
      - user: "kibana"
        role: "readonly"
        password: "kibana"
        tenant: "sftests.com"
        # NOTE: remove after merging:
        # https://softwarefactory-project.io/r/c/software-factory/ansible-role-elastic-recheck/+/22512
        autologin: "basic"
      - user: "zuul"
        role: "admin"
        password: "zuul"
        tenant: "sftests.com"
  tasks:
    # disable ipv6 and others
    - include: common.yaml
      vars:
        sf_install: false

    - include: copy_ssh.yml

    - name: Set hostname
      hostname:
        name: "{{ fqdn }}"

    - name: Ensure that correct hostname is set in hosts file
      become: true
      lineinfile:
        dest: '/etc/hosts'
        regexp: "^{{ fqdn }}.+$"
        line: "{{ ansible_host }} {{ inventory_hostname_short }} {{ fqdn }} elasticsearch.sftests.com elasticsearch"

    - name: Setup ES stack
      include_role:
        name: ansible-role-elastic-recheck
        tasks_from: main.yaml

          #    - name: Run functional tests
          #      include_role:
          #        name: run-opensearch-tox
          #

- hosts: master
  tasks:
    - name: Read ssh key
      delegate_to: elk
      become: true
      shell: |
        cat /root/.ssh/id_ed25519.pub
      register: _host_ssh_pub

    - name: Add ssh pub key access
      become: true
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ _host_ssh_pub.stdout }}"

    - include: copy_ssh.yml
      become: true

    - set_fact:
        elk_ip: "{{ hostvars['elk']['ansible_default_ipv4']['address'] }}"

- hosts: elk
  tasks:
    - name: Read ssh key
      delegate_to: master
      become: true
      shell: |
        cat /root/.ssh/id_ed25519.pub
      register: _host_ssh_pub

    - name: Add ssh pub key access
      become: true
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ _host_ssh_pub.stdout }}"

    - set_fact:
        master_ip: "{{ hostvars['master']['ansible_default_ipv4']['address'] }}"

- hosts: master
  vars:
    add_k1s_hypervisor: true
    # from <CI LOG>/zuul-info/inventory.yaml
    buildset_artifacts_url: ""
    logclassify_debug: true
    logclassify_logserver_dir: logs/
    logclassify_report: true
    sf_arch: allinone
    sf_version: master
    show_hidden_logs: true
    zuul_use_fetch_output: true
  tasks:
    # disable ipv6 and others
    - include: common.yaml

    - name: Prepare instance
      include_role:
        name: '{{ item }}'
      loop:
        #        - prepare-test-env
        #        - install-ci-repository
        - install-sfconfig

    - name: Configure sfconfig
      include_role:
        name: configure-sfconfig
      vars:
        sf_arch: allinone
        static_hostname_ip: '{{ elk_ip }}'
        # FIXME: Change line after renaming elasticsearch to opensearch
        static_hostname_fqdn: "opensearch.sftests.com elasticsearch.sftests.com"
        remove_component:
          # FIXME: change to opensearch when 25354 is merged.
          - component: elasticsearch
          - component: kibana
          - component: logstash

    - name: Configure external_opensearch users
      include_role:
        name: configure-external-elasticsearch-host
      vars:
        kibana_host_url: "http://opensearch.sftests.com:5601"
        readonly_user_autologin: "basic"
        # FIXME: Change line after renaming elasticsearch to opensearh
        elasticsearch_host: opensearch.sftests.com
        opensearch_host: opensearch.sftests.com
        cacert_path: /etc/pki/ca-trust/source/anchors/opensearch.pem
        suffix: sftests_com
        users:
          admin_sftests_com:
            role: admin
            password: admin
          logstash_sftests_com:
            role: logstash
            password: logstash
          # Readonly user
          kibana_sftests_com:
            role: readonly
            password: kibana
          zuul_sftests_com:
            role: zuul
            password: zuul
        opensearch_connections:
          - name: opensearch_sftest_com
            username: zuul_sftests_com
            password: zuul
            host: opensearch.sftests.com
            port: 9200
            use_ssl: true
            ca_certs: /etc/zuul/ssl/opensearch.pem
            index: "zuul"
        # FIXME: change Change line after renaming elasticsearch to opensearch
        elasticsearch_connections:
          - name: opensearch_sftest_com
            username: zuul_sftests_com
            password: zuul
            host: opensearch.sftests.com
            port: 9200
            use_ssl: true
            ca_certs: /etc/zuul/ssl/opensearch.pem
            index: "zuul"
        logstash_host: elasticsearch.sftests.com
        logstash_port: 9998

    - name: Fetch master CA pem file and elasticsearch certs
      include_role:
        name: fetch-ca-pem
      vars:
        instance: elk
        sf_deployment: false

    - name: Run sfconfig
      include_role:
        name: run-sfconfig
      vars:
        sfconfig_args: --provision-demo --enable-insecure-workers

    - name: Ensure test tools are installed
      become: true
      yum:
        name:
          - python3-nose
          - python3-nose-timer
          - python3-nose-htmloutput

    - name: Run functional tests and health-check
      include_role:
        name: '{{ item }}'
      loop:
        # - setup-test-env
        - run-provisioner
        - run-health-check
        - run-functional-tests
