---
- hosts: elk
  become: true
  vars:
    hide_sensitive_logs: false
    fqdn: elasticsearch.sftests.com
    tenant_configuration:
      sftests.com:
        logstash_input_port: 9998
        kibana_autologin: "basic"
    internal_users:
      - user: "admin"
        role: "admin"
        password: "admin"
      - user: "kibanaserver"
        role: "kibanauser"
        password: "kibanaserver"
    users:
      - user: "admin"
        role: "admin"
        password: "admin"
        tenant: "sftests.com"
      - user: "logstash"
        role: "logstash"
        password: "logstash"
        tenant: "sftests.com"
      - user: "curator"
        role: "curator"
        password: "curator"
        tenant: "sftests.com"
      - user: "kibana"
        role: "readonly"
        password: "kibana"
        tenant: "sftests.com"
      - user: "zuul"
        role: "admin"
        password: "zuul"
        tenant: "sftests.com"

  tasks:
    - name: Install rsync package
      become: true
      package:
        name: rsync
        state: present

    - name: Set hostname
      hostname:
        name: "{{ fqdn }}"

    - name: Ensure that correct hostname is set in hosts file
      become: true
      lineinfile:
        dest: '/etc/hosts'
        regexp: "^{{ fqdn }}.+$"
        line: "{{ ansible_host }} {{ inventory_hostname_short }} {{ fqdn }}"

    - name: Setup ES stack
      include_role:
        name: ansible-role-elastic-recheck
        tasks_from: main.yaml
