---
- name: Disable ipv6
  become: true
  shell: |
    sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sysctl -w net.ipv6.conf.default.disable_ipv6=1

- name: Change DNS servers
  become: true
  copy:
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8
    dest: /etc/resolv.conf

- name: Gather package facts
  package_facts:
    manager: auto

- name: Ensure fastestmirror is enabled
  become: true
  lineinfile:
    path: /etc/yum.conf
    regexp: '^fastestmirror'
    line: fastestmirror=1

- name: Increase parallel download
  become: true
  lineinfile:
    path: /etc/yum.conf
    regexp: '^max_parallel_downloads'
    line: max_parallel_downloads=16

- name: Setup fastes mirror when available
  become: true
  copy:
    content: |
      [main]
      socket_timeout = 3
      enabled = 1
      hostfilepath = /var/cache/yum/timedhosts.txt
      maxhostfileage = 1
      always_print_best_host = true
      maxhostfileage=10
      maxthreads=16
      minrate=5M
      exclude=.wcss.pl,.wielun.net
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
  when: "'yum-plugin-fastestmirror' in ansible_facts.packages"

- name: Update all packages
  become: true
  yum:
    name: '*'
    state: latest
  when: update_packages | default(true)

- name: Install base packages
  become: true
  yum:
    name:
      - git
    state: present
