---
- name: Install cert manager required by topolvm
  ansible.builtin.shell: |
    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v{{ cert_manager_version }}/cert-manager.crds.yaml
