---
- name: Prepare host
  ansible.builtin.include_tasks: pre.yaml

- name: Prepare cri-o
  ansible.builtin.include_tasks: crio.yaml

- name: Setup Minikube
  ansible.builtin.include_tasks: minikube.yaml

#- name: Setup helm - required for topolvm
#  ansible.builtin.include_tasks: helm.yaml
#
#- name: Create volume group
#  ansible.builtin.include_tasks: lvm.yaml
#
#- name: Deploy certmanager
#  ansible.builtin.include_tasks: certmanager.yaml
#
#- name: Deploy topolvm
#  ansible.builtin.include_tasks: topolvm.yaml

- name: Post tasks
  ansible.builtin.include_tasks: post.yaml
