---
# Workflow:
# - localhost got file "~/.ansible_crc_vars.yaml" that contains openshift_pull_secret var,
# - localhost spawns crc.dev instance
# - crc.dev is deploying crc
# - after crc is done, comming back to localhost that is executing snapshot withname {{ snapshot_name }}
# - when the snapshot is done, remove the {{ finally_image_name }} - usually it is "centos-{{ centos_release }}-stream-crc"
# - change the "{{ snapshot_name }} to "centos-{{ centos_release }}-stream-crc"
# - remove the crc VM
#
# To setup the venv environment:
# virtualenv  -p /usr/bin/python3 crc-snapshot-venv
# source crc-snapshot-venv/bin/activate
# pip3 install ansible ansible-core==2.13.7 openstackclient python-openstackclient
# ansible-galaxy collection install  community.general community.crypto ansible.posix openstack.cloud
#
# Run playbook with following command:
#
# ansible-playbook -e "ansible_host_key_checking=False" -e "centos_release=9" playbooks/crc-make-snapshot.yaml
#
### NOTE: c8s crc image will be removed soon.
#
# ansible-playbook -e "ansible_host_key_checking=False" -e "centos_release=8" -e "image_name=upstream-centos-8-stream-1687102218" playbooks/crc-make-snapshot.yaml
#
# Additional variables:
### openstack - preparations ###
# - define image_name
# - define image_ssh_user
### crc ###
# - crc_parameters: "--memory 14336 --disk-size 60 --cpus 6"
#
# NOTE: Playbook requires: ansible-galaxy collection install openstack.cloud
# If it's not updated, it can raise an error:
# openstack.cloud.server error 'volumes is not found. openstack.compute.v2.server.Server objects do not support setting arbitrary keys through the dict interface.
#
# NOTE: The snapshot is using image: cloud-centos-9-stream-tripleo that is using
# "zuul" as regular user. More info: https://softwarefactory-project.io/r/c/software-factory/sf-infra/+/28356/comments/b4d1830e_5060e846
#

# This playbook deploy crc and prepare VM to make a snapshot, that later
# can be deployed in CI.
- name: Deploy CRC
  hosts: crc.dev
  vars:
    # for extra/crc role
    crc_debug: true
    prepare_sfoperator: false
    # optional
    # crc_parameters: "--memory 14336 --disk-size 60 --cpus 6"
    crc_version: 2.32.0
  pre_tasks:
    #    - name: Read file with openshift_pull_secret
    #      ansible.builtin.include_vars:
    #        file: ~/.ansible_crc_vars.yaml
    #      delegate_to: localhost
  roles:
    - extra/crc
    - next-gen/extracted-crc
