---
- hosts: microshift.dev
  vars:
    fqdn: microshift.dev
    # pv_storageclass: standard
    pv_count:
      start: 1
      end: 12
    microshift_version: 4.12
    overwrite_container_policy: false
    setup_olm: true
    microshift_additional_addresses:
      - "{{ fqdn }}"
      - "sftests.com"
      - "example.com"
  tasks:
    - name: Setup Microshift
      block:
        - name: Start Microshift deployment
          include_role:
            name: ansible-microshift-role

        - name: Create script to verify deployment
          copy:
            content: |
              for i in {1..20}; do
                echo "Ensuring that containers are spawned... ${i}"
                count=$(/usr/local/bin/oc get pods --all-namespaces | grep openshift | grep -viE 'running' -c)
                if [ "$count" -eq "0" ]; then
                    echo "Microshift is deployed, we can continue..."
                    break
                else
                    echo "The Microshift containers are not ready..."
                    sleep 15
                fi
              done
            dest: /tmp/pull-images.sh
            mode: "0755"

        - name: Check if all containers are up and ready
          shell: /tmp/pull-images.sh
