---
- name: Deploy Kind
  hosts: kind.dev
  vars:
    kind_version: "v0.14.0"
    kubernetes_version: "v1.24.1"
    deploy_tools: true
  tasks:
    - name: Install required packages
      become: true
      package:
        name:
          - podman
          - golang
          - bash-completion
        state: present

    - name: Download kind
      become: true
      get_url:
        url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
        dest: /usr/local/bin/kind
        mode: '0755'

    - name: Download kubectl
      become: true
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Create dedicated directory for kind src
      become: true
      file:
        path: "/home/{{ ansible_user }}/src"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy config file
      become: true
      copy:
        content: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            networking:
              apiServerAddress: {{ ansible_default_ipv4.address }}
              apiServerPort: 6443
            nodes:
            - role: control-plane
              extraMounts:
              - hostPath: /home/{{ ansible_user }}/src
                containerPath: /tmp/src
                readOnly: false
                selinuxRelabel: false
                propagation: HostToContainer
              kubeadmConfigPatches:
                - |
                  kind: InitConfiguration
                  nodeRegistration:
                    kubeletExtraArgs:
                      node-labels: "ingress-ready=true"
                  extraPortMappings:
                  - containerPort: 80
                    hostPort: 80
                    protocol: TCP
                  - containerPort: 443
                    hostPort: 443
                    protocol: TCP
            #- role: worker
            #  extraMounts:  # Share the host filesystem
            #  - hostPath: "/home/{{ ansible_user }}/src"
            #    containerPath: /src

        dest: /etc/kind-config.yaml
        mode: "0644"

    - name: Deploy kind
      become: true
      shell: |
        /usr/local/bin/kind create cluster --config /etc/kind-config.yaml &> ~/kind-cluster-log

    - name: Get kind cluster configuration
      become: true
      shell: |
        mkdir -p ~/.kube
        /usr/local/bin/kind get kubeconfig > ~/.kube/config
        /usr/local/bin/kubectl completion bash > /etc/bash_completion.d/kubectl
        echo "export PATH=\$PATH:/usr/local/bin" >> ~/.bashrc

    - name: Setup ingress controller
      become: true
      shell: |
        /usr/local/bin/kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

    - name: Download additional tools
      include_tasks: k8s-tools.yaml
      when: deploy_tools

    - name: Change system settings
      include_tasks: additional-settings.yaml
