---
# NOTE: REMEMBER TO ADD pull-secret.txt content into: playbooks/custom/group_vars/all
- hosts: crc.dev
  vars:
    crc_debug: true
    prepare_sfoperator: false
  pre_tasks:
    - name: Update packages
      become: true
      package:
        name: '*'
        state: latest

    - name: Ensure CentOS runs with selinux permissive
      become: true
      selinux:
        policy: targeted
        state: permissive

    - name: Install packages
      become: true
      yum:
        name:
          - make
          - git
          - vim
          - golang
          - tar
          - ansible-core
          - skopeo
          - sqlite
          - jq
          - podman
        state: present
  roles:
    - extra/crc
  post_tasks:
    - name: Ensure cloud-init is installed
      become: true
      package:
        name:
          - cloud-init
          - golang
        state: present
    - name: Cleanup dnf cache
      become: true
      shell: dnf clean all
    # dpawlik: for some reason, ssh local keys in /etc/ssh/ are not generated during start.
    - name: Create crontab entry to generate local ssh keys
      become: true
      copy:
        content: |
          @reboot root /usr/bin/ssh-keygen -A; systemctl start sshd
        dest: /etc/cron.d/ssh_gen

    - name: Set proper selinux label
      become: true
      shell: |
        /usr/bin/chcon system_u:object_r:system_cron_spool_t:s0 /etc/cron.d/ssh_gen

    - name: Remove pull-secret.txt file
      file:
        path: pull-secret.txt
        state: absent
      register: _cleanup_pull_secret
